### ISSUE TITLE
Crash on Month Change

### ISSUE THREAD

**Issue by dougiep77** [baywolf-studios/BudgetBadger#84]
**Describe the bug**
When changing months (forward or backward) the app crashes.

**To Reproduce**
1. Open the app and navigate to the 'envelopes' screen
2. Click either arrow next to the current month
3. The app crashes

**Expected behavior**
I would expect to change to either the prior or next month's budget/envelopes.

**Screenshots**
The app crashes to quickly to get a screen shot.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS
 - Version  15.6

**Additional context**
The same crash occurs on both my iPhone and my Windows PC

**Comment by matthewpritchett** [comment]
Did it happen with a fresh install on both devices? I don’t experience crashing when changing months on any of my test devices so it’s definitely puzzling. I’m wondering if maybe some data got into a bad state causing the crash is my first thought. I’ll have to try to recreate it and see if I can get it to happen.

**Comment by dougiep77** [comment]
Interesting... Yeah, I installed it last night on my iPhone but didn't try changing months. I then installed it today on my PC and that is when I had my first crash. So, I went back to my iPhone app and noticed it did the same thing. I have only added a few accounts and setup the Drop Box sync. Maybe it has something to do with that? I turned it off, but it still crashes. I'll try my Android out later tonight.

**Comment by dougiep77** [comment]
I tried it on my Android tablet and it switched months just fine. Then I realized that I wasn’t connected to the internet. Once I connected the app started crashing when changing months.

**Comment by matthewpritchett** [comment]
Definitely sounds like some bad data then. Which is so weird as I have stuff in place to prevent stuff like this. Unfortunately the quickest for you is likely to uninstall and delete the folder in Dropbox, then reinstall it all if you aren’t too far in. I’ll try to break some of mine with bad data in the meantime.

**Comment by dougiep77** [comment]
I must have messed up something when I started entering my data. I followed the steps you gave and it’s working now. Thanks so much for your help! I really appreciate it!

Doug

**Comment by dougiep77** [comment]
Got it working on all my devices, entered my accounts and now it started crashing again like before. So weird…

**Comment by matthewpritchett** [comment]
If you’re comfortable, could you email me the file that’s in the Dropbox folder for Budget Badger? I’d be able to debug the issue. Totally understandable if you don’t want to though. Maybe you could rename or clear out the amounts before sending if that was a concern. I unfortunately can’t really replicate it on my stuff so far. I’m guessing something unique in your setup is causing it.

support@budgetbadger.io

**Comment by dougiep77** [comment]
Yeah, must have something to do with that. I just sent the file. Thanks!

**Comment by matthewpritchett** [comment]
Thank you! Found the issue and got a fix building. Will let you know once it's submitted to the various app stores.

**Comment by dougiep77** [comment]
That’s great! Thanks for your help!

**Comment by dougiep77** [comment]
I got the latest apps and they are all working well. I tried starting over and deleted by cloud sync file and reinstalling. My ios app opens with no data, but the android app seems to be keeping a local copy of my data. It's not setup to sync but its still showing data even after the reinstall. Any idea why? Thanks!

**Comment by matthewpritchett** [comment]
I’m not entirely sure on how Android handles uninstalls but I’m guessing either there’s a google backup or the actual application data doesn’t get cleared on an uninstall due to some setting. If all else fails, you should be able to delete all the transactions in accounts, hide the accounts and payees, then delete them if you wanted to. Unfortunately I haven’t got a reset function in the app as I assumed it would handle that on uninstall like it does for iOS.

I logged a feature #86 to capture that idea.

**Comment by dougiep77** [comment]
Got it to work. Thanks again! From: Matthew PritchettSent: Sunday, September 18, 2022 10:27 AMTo: baywolf-studios/BudgetBadgerCc: dougiep77; AuthorSubject: Re: [baywolf-studios/BudgetBadger] Crash on Month Change (Issue #84) I’m not entirely sure on how Android handles uninstalls but I’m guessing either there’s a google backup or the actual application data doesn’t get cleared on an uninstall due to some setting. If all else fails, you should be able to delete all the transactions in accounts, hide the accounts and payees, then delete them if you wanted to. Unfortunately I haven’t got a reset function in the app as I assumed it would handle that on uninstall like it does for iOS.I logged a feature #86 to capture that idea.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by dougiep77** [comment]
I noticed on my iPhone that I can move forward and then backwards to the current month (Sept - where my data starts) without it crashing but if I go back to August, where I don’t have any data, it crashes.

**Comment by matthewpritchett** [comment]
Sorry for late reply, that’s super strange as the fix I had done should have fixed that but I have your file you sent still so I’ll try to play around and reproduce it and see. I’m assuming it doesn’t cause issues with using since there isn’t any data in those months anyway? Thanks!
